import type { Project, StageId } from "./types"
import { STAGES } from "./types"

export function toUIProject(p: any): Project {
  const understandingInsights = (p.understanding?.insights || []) as any[]
  const workshopInsights = (p.workshop?.insights || []) as any[]
  const quoteServices = Array.isArray(p.quote?.services) ? p.quote.services : []

  return {
    id: p.id,
    name: p.name,
    client: p.client,
    type: p.type,
    stage: p.stage as StageId,
    progress: p.progress,
    status: p.status,
    lastActivity: p.lastActivity?.toISOString?.() || p.lastActivity || new Date().toISOString(),
    nextAction: p.nextAction,
    owner: "—",
    aiActivity: p.aiActivity,
    brief: {
      clientInfo: { name: p.brief?.clientName || "", company: p.brief?.company || "", contact: p.brief?.contact || "", industry: p.brief?.industry || "" },
      title: p.brief?.title || "",
      businessObjective: p.brief?.businessObjective || "",
      objectives: p.brief?.objectives || [],
      audience: p.brief?.audience || "",
      brand: p.brief?.brand || "",
      direction: p.brief?.direction || "",
      deliverables: p.brief?.deliverables || [],
      budget: p.brief?.budget || "",
      timeline: p.brief?.timeline || "",
      attachments: p.brief?.attachments || [],
      context: p.brief?.context || "",
      aiAnalysis: {
        wants: p.brief?.aiWants || [],
        keyObjectives: p.brief?.aiObjectives || [],
        requirements: p.brief?.aiRequirements || [],
        risks: p.brief?.aiRisks || [],
        missing: p.brief?.aiMissing || [],
        questions: p.brief?.aiQuestions || [],
        confidence: p.brief?.aiConfidence || 0,
      },
    },
    call: {
      date: p.call?.date || "—",
      participants: p.call?.participants || [],
      duration: p.call?.duration || "—",
      summary: p.call?.summary || "",
      meetingSource: p.call?.meetingSource || "",
      transcript: p.call?.transcript || "",
    },
    transcript: {
      moments: Array.isArray(p.transcript?.moments) ? p.transcript.moments : [],
      decisions: p.transcript?.decisions || [],
      actions: Array.isArray(p.transcript?.actions) ? p.transcript.actions : [],
      requirements: p.transcript?.requirements || [],
      text: Array.isArray(p.transcript?.lines) ? p.transcript.lines.map((l: any) => ({ speaker: l.speaker, role: l.role as any, text: l.text })) : [],
    },
    understanding: {
      confidence: p.understanding?.confidence || 0,
      wants: understandingInsights.filter((i) => i.group === "wants"),
      businessObjectives: understandingInsights.filter((i) => i.group === "businessObjectives"),
      creativeObjectives: understandingInsights.filter((i) => i.group === "creativeObjectives"),
      constraints: understandingInsights.filter((i) => i.group === "constraints"),
      risks: understandingInsights.filter((i) => i.group === "risks"),
      missing: understandingInsights.filter((i) => i.group === "missing"),
      questions: understandingInsights.filter((i) => i.group === "questions"),
    },
    projectBrief: {
      summary: p.projectBrief?.summary || "",
      businessObjective: p.projectBrief?.businessObjective || "",
      creativeObjective: p.projectBrief?.creativeObjective || "",
      audience: p.projectBrief?.audience || "",
      direction: p.projectBrief?.direction || "",
      deliverables: p.projectBrief?.deliverables || [],
      timeline: p.projectBrief?.timeline || "",
      budget: p.projectBrief?.budget || "",
      risks: p.projectBrief?.risks || [],
      openQuestions: p.projectBrief?.openQuestions || [],
      successCriteria: p.projectBrief?.successCriteria || [],
    },
    workshop: {
      humanNotes: p.workshop?.humanNotes || "",
      questions: workshopInsights.filter((i) => i.group === "questions"),
      brandInsights: workshopInsights.filter((i) => i.group === "brandInsights"),
      audienceInsights: workshopInsights.filter((i) => i.group === "audienceInsights"),
      opportunities: workshopInsights.filter((i) => i.group === "opportunities"),
      challenges: workshopInsights.filter((i) => i.group === "challenges"),
      directions: workshopInsights.filter((i) => i.group === "directions"),
    },
    synthesis: {
      executiveSummary: p.synthesis?.executiveSummary || "",
      strategicDirection: p.synthesis?.strategicDirection || "",
      creativeDirection: p.synthesis?.creativeDirection || "",
      approach: p.synthesis?.approach || "",
      deliverables: p.synthesis?.deliverables || [],
      timeline: p.synthesis?.timeline || "",
      risks: p.synthesis?.risks || [],
      openQuestions: p.synthesis?.openQuestions || [],
      decisions: p.synthesis?.decisions || [],
    },
    proposal: {
      clientDetails: p.proposal?.clientDetails || "",
      overview: p.proposal?.overview || "",
      problem: p.proposal?.problem || "",
      solution: p.proposal?.solution || "",
      scope: p.proposal?.scope || [],
      deliverables: p.proposal?.deliverables || [],
      timeline: p.proposal?.timeline || "",
      team: p.proposal?.team || [],
      investment: p.proposal?.investment || "",
      terms: p.proposal?.terms || "",
      status: (p.proposal?.status || "draft") as any,
      sections: Array.isArray(p.proposal?.sections) ? p.proposal.sections : [],
    },
    quote: {
      services: quoteServices,
      discount: p.quote?.discount || 0,
      tax: p.quote?.tax || 0,
      paymentTerms: p.quote?.paymentTerms || "",
      status: (p.quote?.status || "draft") as any,
    },
    contactReport: {
      summary: p.contactReport?.summary || "",
      keyPoints: p.contactReport?.keyPoints || [],
      decisions: p.contactReport?.decisions || [],
      actionItems: Array.isArray(p.contactReport?.actionItems) ? p.contactReport.actionItems : [],
      nextSteps: p.contactReport?.nextSteps || [],
      approved: p.contactReport?.approved || false,
      sentToClient: p.contactReport?.sentToClient || false,
      sentAt: p.contactReport?.sentAt?.toISOString?.() || p.contactReport?.sentAt || undefined,
    },
    productionMeeting: {
      decision: p.productionMeeting?.decision || "",
      notes: p.productionMeeting?.notes || undefined,
    },
  }
}
